# GENERATED by scripts/gen_manifest.py from registry/*.md — do not hand-edit.
# Sourced by scripts/bootstrap.sh. Signature: clone_repo <url> <bucket-dir> <slug>

clone_repo "https://github.com/nmalick/Qari.git" "personal-projects" "Qari"
clone_repo "https://github.com/nmalick/art_is_everywear.git" "freelance-projects" "art_is_everywear"
clone_repo "https://github.com/nmalick/bil-app.git" "pocs" "bil-app"
clone_repo "https://github.com/nmalick/emnlabs_site.git" "personal-projects" "emnlabs_site"
clone_repo "https://github.com/nmalick/qari-assets.git" "personal-projects" "qari-assets"
