# GENERATED by scripts/gen_manifest.py from registry/*.md — do not hand-edit.
# Sourced by scripts/bootstrap.sh. Signature: clone_repo <url> <bucket-dir> <slug>
# PUBLIC manifest: repo_public entries only. Private/client clone lines live in the
# gitignored manifest.local.sh (also maintained by this script, never committed).

clone_repo "https://github.com/nmalick/qari-assets.git" "personal-projects" "qari-assets"
