#!/usr/bin/env python3
"""
catalog_sync — EMN_labOS catalog + AI-ops generator (v2, 2026-08 rebuild).

Source of truth: registry/<project>.md frontmatter (flat scalars — see scripts/lib/registry.py).
Eligibility (default-deny): visibility ∈ {public, anonymized} AND (live_url OR repo_public
OR showcase: true). Everything else is omitted from every public surface, loudly.

Emits (regenerated, never hand-edited):
  projects.json · README.md · STATUS.md · ROADMAP.md · RELEASE-NOTES.md
  docs/index.html · docs/ai-ops.html · docs/projects-corpus.json
  registry/<slug>-index.md   (generated pointer index per eligible project)

Properties:
- `--check` passes IFF a write run would change nothing: render in memory, diff against
  the working tree (plus orphaned index files), exit 1 on drift, writing nothing. It holds
  on a clean checkout (CI) because nothing rendered depends on untracked state or git
  history — the two inputs a clean checkout cannot reproduce are carried forward instead:
  * the "as of" stamp: kept from the committed STATUS.md while the stamped surfaces are
    otherwise unchanged; set to the generation date only when their content changes.
    Never derived from git — a squash-merge (or the commit carrying the regeneration)
    re-dates any commit-derived stamp after generation. (2026-09 fix)
  * kit-derived content (registry/<slug>-index.md body, corpus doc_index): read from the
    project's gitignored project-os/ when the project folder is on disk; carried forward
    from the committed artifact when it is not (CI, an un-cloned bucket). An absent folder
    means UNKNOWN, not "no kit". (2026-09 fix)
- No tombstones: registry/*-index.md with no eligible entry behind it is deleted on write
  and reported as drift by --check (the repo is public; a stale index names the project).
- Every public surface passes through registry.public_record() (allowlist) — there is
  no other path from an entry to output. mcps never emits for freelance-bucket entries.
- Every generated artifact opens with a generated-by-automation disclaimer.
- Empty output with eligible entries is an error.
"""
import datetime
import glob
import html
import json
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
import registry as R  # noqa: E402

GEN_MD = "<!-- GENERATED by scripts/catalog_sync.py from registry/*.md — do not hand-edit. Generated by automation; may contain inaccuracies — verify against the repo. -->\n"
DISCLAIMER_HTML = "<p class=\"meta\">Generated by automation from <code>registry/</code> — may contain inaccuracies; verify against the repo.</p>"
INDEX_INTRO = "_Generated pointer into the project's own `project-os/`; content lives in the project repo._"
NO_KIT = "_No project-os doc kit yet (pre-baseline)._"
CORPUS = os.path.join("docs", "projects-corpus.json")
# Artifacts that carry the "as of" stamp; STATUS.md is where the committed stamp is read back.
STAMPED = ("README.md", "STATUS.md", "ROADMAP.md", "RELEASE-NOTES.md", os.path.join("docs", "index.html"))
STAMP_RE = re.compile(r"^_As of the latest registry change: (.+)_$", re.M)


def md_escape(s):
    return str(s).replace("|", "\\|")


def write(root, path, content):
    full = os.path.join(root, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)


def read_text(root, path):
    full = os.path.join(root, path)
    if not os.path.isfile(full):
        return None
    with open(full, encoding="utf-8") as f:
        return f.read()


def index_path(slug):
    return os.path.join("registry", f"{slug}-index.md")


def load_prior(root):
    """Committed state a clean checkout cannot regenerate: the "as of" stamp and the
    kit-derived fragments, keyed by slug. Only ever consulted for still-eligible slugs."""
    prior = {"asof": None, "index_body": {}, "doc_index": {}}
    stamp = STAMP_RE.search(read_text(root, "STATUS.md") or "")
    if stamp:
        prior["asof"] = stamp.group(1)
    for full in glob.glob(os.path.join(root, "registry", "*-index.md")):
        name = os.path.basename(full)
        _, sep, body = (read_text(root, os.path.join("registry", name)) or "").partition(INDEX_INTRO + "\n\n")
        if sep:
            prior["index_body"][name[:-len("-index.md")]] = body
    try:
        for rec in json.loads(read_text(root, CORPUS) or "[]"):
            if isinstance(rec, dict) and isinstance(rec.get("doc_index"), dict):
                prior["doc_index"][rec.get("slug")] = rec["doc_index"]
    except ValueError:
        pass
    return prior


def read_project_index(m):
    """Pointer-index inputs from the project's own project-os/ (read from local disk;
    pointers only, never content copies). None = project folder not on this machine
    (gitignored bucket absent, e.g. CI): the kit is UNKNOWN, not empty."""
    pdir = R.project_dir(m)
    if not pdir or not os.path.isdir(pdir):
        return None
    out = {"reference_rows": [], "cursor": "", "has_kit": False}
    d = os.path.join(pdir, "project-os", "DIRECTORY.md")
    if os.path.isfile(d):
        out["has_kit"] = True
        for line in open(d, encoding="utf-8", errors="replace"):
            if line.strip().startswith("|") and line.count("|") >= 3 and "---" not in line:
                out["reference_rows"].append(line.rstrip())
    arch = os.path.join(pdir, "project-os", "engineering", "architecture.md")
    if os.path.isfile(arch):
        for line in open(arch, encoding="utf-8", errors="replace"):
            if "Last commit checked" in line:
                out["cursor"] = line.strip().lstrip(">* ").strip()
                break
    return out


def kit_fragments(idx):
    """The kit-derived pieces of the output: (index body, corpus doc_index)."""
    body = []
    if idx["cursor"]:
        body.append(f"> {idx['cursor']}\n")
    if idx["reference_rows"]:
        body += idx["reference_rows"]
    elif idx["has_kit"]:
        body.append("_project-os present; DIRECTORY has no reference rows yet._")
    else:
        body.append(NO_KIT)
    return "\n".join(body) + "\n", {"has_kit": idx["has_kit"], "cursor": idx["cursor"]}


def resolve_kit(m, prior):
    """Fresh from disk when the project folder is present; otherwise carried forward from
    the committed artifacts (placeholder only if nothing was ever committed)."""
    idx = read_project_index(m)
    if idx is not None:
        return kit_fragments(idx)
    body, doc_index = kit_fragments({"reference_rows": [], "cursor": "", "has_kit": False})
    old = prior["doc_index"].get(m["slug"])
    if old is not None:  # re-allowlisted: a hand-added corpus key never survives a regen
        doc_index = {"has_kit": bool(old.get("has_kit")), "cursor": str(old.get("cursor") or "")}
    return prior["index_body"].get(m["slug"], body), doc_index


def render_all(shown, asof, prior=None):
    """Return {relpath: content} for every artifact. `prior` (see load_prior) supplies the
    kit-derived content for projects whose folder is not on this machine."""
    prior = prior or {"index_body": {}, "doc_index": {}}
    kits = {m["slug"]: resolve_kit(m, prior) for m in shown}
    arts = {}

    arts["projects.json"] = json.dumps([R.public_record(m) for m in shown], indent=2) + "\n"

    # README.md
    r = [GEN_MD, "# EMN_labOS\n",
         "**The lab operating system**: a public umbrella for Malick Ndiaye's private projects — "
         "part machine OS (identity separation, replication, config hygiene), part showcase "
         "(project inventory + the AI-operations architecture itself). Projects live as private "
         "repos; this repo publishes only registry-gated metadata and the OS tooling.\n",
         f"_Catalog as of the latest registry change: {asof}_\n", "## Projects\n"]
    if shown:
        r.append("| Project | Summary | Stack | Links |")
        r.append("|---|---|---|---|")
        for m in shown:
            links = []
            if (m.get("live_url") or "").strip():
                links.append(f"[live]({m['live_url']})")
            if m.get("repo_public") and (m.get("repo_url") or "").strip():
                links.append(f"[repo]({m['repo_url']})")
            if not links:
                links.append("in development")
            r.append(f"| {md_escape(m['name'])} | {md_escape(m.get('summary',''))} | "
                     f"{md_escape(', '.join(m['stack']))} | {', '.join(links)} |")
    else:
        r.append("_No public projects yet._")
    r += ["", "## The OS itself",
          "The showcase artifact is this repo's structure: registry-driven generated catalog "
          "(default-deny), identity-wall git hooks, machine replication (`scripts/bootstrap.sh`), "
          "an allowlist-synthesized public config snapshot (`home-claude/`), and the AI-ops "
          "surface ([docs/ai-ops.html](docs/ai-ops.html)). Start at [DIRECTORY.md](DIRECTORY.md)."]
    arts["README.md"] = "\n".join(r) + "\n"

    # STATUS.md
    s = [GEN_MD, "# Status\n", f"_As of the latest registry change: {asof}_\n",
         "| Project | Bucket | Status | Live |", "|---|---|---|---|"]
    for m in shown:
        live = f"[{m['live_url']}]({m['live_url']})" if (m.get("live_url") or "").strip() else "—"
        s.append(f"| {md_escape(m['name'])} | {m['bucket']} | {m['status']} | {live} |")
    if not shown:
        s.append("| _none_ | | | |")
    arts["STATUS.md"] = "\n".join(s) + "\n"

    # ROADMAP.md
    rm = [GEN_MD, "# Roadmap\n", f"_As of the latest registry change: {asof}_\n",
          "Public projects grouped by status. Private/unlisted projects are omitted by design.\n"]
    by_status = {}
    for m in shown:
        by_status.setdefault(m["status"], []).append(m["name"])
    if by_status:
        for st in sorted(by_status):
            rm.append(f"## {st}")
            rm += [f"- {n}" for n in by_status[st]]
            rm.append("")
    else:
        rm.append("_No public projects yet._")
    arts["ROADMAP.md"] = "\n".join(rm) + "\n"

    # RELEASE-NOTES.md
    rn = [GEN_MD, "# Release notes\n", f"_As of the latest registry change: {asof}_\n"]
    live_entries = [m for m in shown if (m.get("live_url") or "").strip()]
    if live_entries:
        rn += [f"- **{md_escape(m['name'])}** — live at [{m['live_url']}]({m['live_url']})."
               for m in live_entries]
    else:
        rn.append("_No public releases yet._")
    arts["RELEASE-NOTES.md"] = "\n".join(rn) + "\n"

    # docs/index.html
    cards = "\n".join(
        f'    <article class="card"><h2>{html.escape(m["name"])}</h2>'
        f'<p>{html.escape(m.get("summary",""))}</p>'
        f'<p class="stack">{html.escape(", ".join(m["stack"]))}</p>'
        + (f'<a href="{html.escape(m["live_url"], quote=True)}">{html.escape(m["live_url"])}</a>'
           if (m.get("live_url") or "").strip() else '<span class="stack">in development</span>')
        + '</article>'
        for m in shown
    ) or '    <p>No public projects yet.</p>'
    arts[os.path.join("docs", "index.html")] = f"""<!doctype html>
<!-- GENERATED by scripts/catalog_sync.py — do not hand-edit. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EMN_labOS — Projects</title>
<style>
 body{{font-family:system-ui,sans-serif;max-width:880px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}}
 h1{{margin-bottom:.25rem}} .meta{{color:#666;font-size:.9rem}}
 .grid{{display:grid;gap:1rem;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));margin-top:1.5rem}}
 .card{{border:1px solid #e3e3e3;border-radius:12px;padding:1rem}}
 .card h2{{margin:.2rem 0;font-size:1.1rem}} .stack{{color:#666;font-size:.85rem}}
 .card a{{word-break:break-all}}
 nav a{{margin-right:1rem}}
</style></head><body>
 <h1>EMN_labOS</h1>
 {DISCLAIMER_HTML}
 <p class="meta">As of the latest registry change: {asof} — registry-gated public projects only.</p>
 <nav><a href="ai-ops.html">AI operations →</a></nav>
 <div class="grid">
{cards}
 </div>
</body></html>
"""

    # docs/ai-ops.html — allowlisted fields + label-keyed personal MCP profile +
    # hand-authored prose (registry/ai-ops-prose.md; NEVER generated from hooks source).
    prose_path = os.path.join(R.ROOT, "registry", "ai-ops-prose.md")
    prose_html = ""
    if os.path.isfile(prose_path):
        prose_md = open(prose_path, encoding="utf-8").read()
        paras = [p.strip() for p in prose_md.split("\n\n")
                 if p.strip() and not p.strip().startswith("#") and not p.strip().startswith("<!--")]
        prose_html = "\n".join(f"<p>{html.escape(p)}</p>" for p in paras)
    mcp_rows = ""
    accounts_path = os.path.join(R.ROOT, "home-claude", "mcp-accounts.json")
    if os.path.isfile(accounts_path):
        try:
            accounts = json.load(open(accounts_path))
            for grp in accounts.values():
                for mcp in grp.get("mcps", []):
                    mcp_rows += f"<li>{html.escape(mcp)}</li>\n"
        except Exception:
            pass
    proj_mcps = ""
    for m in shown:
        rec = R.public_record(m)
        if rec.get("mcps"):
            proj_mcps += (f"<tr><td>{html.escape(m['name'])}</td>"
                          f"<td>{html.escape(', '.join(rec['mcps']))}</td></tr>\n")
    arts[os.path.join("docs", "ai-ops.html")] = f"""<!doctype html>
<!-- GENERATED by scripts/catalog_sync.py — do not hand-edit. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EMN_labOS — AI Operations</title>
<style>
 body{{font-family:system-ui,sans-serif;max-width:880px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}}
 .meta{{color:#666;font-size:.9rem}} table{{border-collapse:collapse;width:100%}}
 td,th{{border:1px solid #e3e3e3;padding:.5rem;text-align:left}}
 nav a{{margin-right:1rem}}
</style></head><body>
 <h1>AI Operations</h1>
 {DISCLAIMER_HTML}
 <nav><a href="index.html">← Projects</a></nav>
 <section><h2>How this OS runs</h2>
{prose_html or "<p>(architecture notes pending)</p>"}
 </section>
 <section><h2>Personal MCP profile</h2>
 <ul>
{mcp_rows or "<li>(none published)</li>"}
 </ul></section>
 <section><h2>Per-project MCP usage</h2>
 <table><tr><th>Project</th><th>MCP servers</th></tr>
{proj_mcps or "<tr><td colspan=2>(populated as project baselines land)</td></tr>"}
 </table></section>
</body></html>
"""

    # docs/projects-corpus.json — the future-ingestion contract (Friday / portfolio reports).
    corpus = []
    for m in shown:
        rec = R.public_record(m)
        rec["doc_index"] = kits[m["slug"]][1]
        corpus.append(rec)
    arts[CORPUS] = json.dumps(corpus, indent=2) + "\n"

    # registry/<slug>-index.md — generated pointer index per eligible project.
    for m in shown:
        head = "\n".join([GEN_MD, f"# {m['name']} — doc index (pointer)\n", INDEX_INTRO + "\n"]) + "\n"
        arts[index_path(m["slug"])] = head + kits[m["slug"]][0]

    return arts


def drifted(arts, root):
    """Artifacts whose rendered content differs from the working tree."""
    return [p for p, c in arts.items() if read_text(root, p) != c]


def stale_indexes(arts, root):
    """registry/*-index.md on disk with no eligible entry behind it — tombstones."""
    on_disk = {index_path(os.path.basename(p)[:-len("-index.md")])
               for p in glob.glob(os.path.join(root, "registry", "*-index.md"))}
    return sorted(on_disk - set(arts))


def plan(shown, prior, root, today):
    """Render with the committed stamp; restamp with `today` only when a stamped surface's
    content actually changed. This is what makes --check == "a write would be a no-op"."""
    asof = prior.get("asof") or today
    arts = render_all(shown, asof, prior)
    if asof != today and set(drifted(arts, root)) & set(STAMPED):
        arts = render_all(shown, today, prior)
    return arts


def apply(arts, changed, orphans, root):
    # Orphans first: on a case-insensitive filesystem a slug re-cased in the registry would
    # otherwise have its freshly written index deleted as the "old" spelling.
    for p in orphans:
        os.remove(os.path.join(root, p))
    for p in changed:
        write(root, p, arts[p])


def main():
    check = "--check" in sys.argv
    entries, load_errors = R.load()
    errors = load_errors + R.validate(entries)
    if errors:
        print("catalog_sync: REGISTRY INVALID — refusing to generate:", file=sys.stderr)
        for e in errors:
            print(f"  ✗ {e}", file=sys.stderr)
        sys.exit(2)

    shown = [m for m in entries if R.is_public(m)]
    omitted = [m for m in entries if not R.is_public(m)]
    arts = plan(shown, load_prior(R.ROOT), R.ROOT, datetime.date.today().isoformat())

    for path, content in arts.items():
        if shown and not content.strip():
            print(f"catalog_sync: EMPTY artifact {path} with {len(shown)} eligible entries", file=sys.stderr)
            sys.exit(2)

    changed, orphans = drifted(arts, R.ROOT), stale_indexes(arts, R.ROOT)
    carried = [m["name"] for m in shown if read_project_index(m) is None]

    if check:
        if changed or orphans:
            print("catalog_sync --check: DRIFT in:", file=sys.stderr)
            for p in changed:
                print(f"  ✗ {p}", file=sys.stderr)
            for p in orphans:
                print(f"  ✗ {p} (orphan: no eligible registry entry — a write run deletes it)", file=sys.stderr)
            print("Fix: python3 scripts/catalog_sync.py, then commit the result.", file=sys.stderr)
            sys.exit(1)
        print(f"catalog_sync --check: clean ({len(arts)} artifacts, {len(shown)} shown"
              f"{f'; kit content carried forward for {len(carried)} (project folder not on disk)' if carried else ''}).")
        return

    apply(arts, changed, orphans, R.ROOT)

    print(f"catalog_sync: {len(shown)} shown, {len(omitted)} omitted, {len(arts)} artifacts, "
          f"{len(changed)} changed, {len(orphans)} removed.")
    for m in shown:
        tag = m.get("live_url") or ("public repo" if m.get("repo_public") else "showcase")
        kit = " [kit carried forward: project folder not on disk]" if m["name"] in carried else ""
        print(f"  SHOWN   {m['name']} -> {tag}{kit}")
    for m in omitted:
        print(f"  OMITTED {m.get('name','?')} ({m.get('_file')}) — {R.omit_reason(m)}")
    for p in orphans:
        print(f"  REMOVED {p} (no eligible registry entry)")


if __name__ == "__main__":
    main()
