#!/usr/bin/env python3
"""
catalog_sync — EMN_labOS catalog generator.

Source of truth: registry/<project>.md frontmatter.
Default-deny: a project reaches PUBLIC surfaces only if
  visibility in {public, anonymized} AND live_url is non-empty.
Emits (regenerated, never hand-edited):
  projects.json, README.md, STATUS.md, ROADMAP.md, RELEASE-NOTES.md, docs/index.html
Prints an "omitted (why)" summary each run.
Generalized from the JourneyOS /guide-sync pattern. Stdlib only.
"""
import json, glob, os, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = os.path.join(ROOT, "registry")
PUBLIC_VIS = {"public", "anonymized"}
PUBLIC_FIELDS = ["name", "slug", "bucket", "status", "stack", "live_url", "summary"]


def parse_frontmatter(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        return None
    body = text.split("---", 2)
    if len(body) < 3:
        return None
    meta = {}
    for line in body[1].strip().splitlines():
        if ":" not in line:
            continue
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip()
    # normalize stack -> list
    stack = meta.get("stack", "")
    meta["stack"] = [s.strip() for s in stack.split(",") if s.strip()]
    meta["repo_public"] = str(meta.get("repo_public", "")).lower() == "true"
    return meta


def load_registry():
    entries = []
    for p in sorted(glob.glob(os.path.join(REG, "*.md"))):
        if os.path.basename(p).lower() == "readme.md":
            continue
        m = parse_frontmatter(p)
        if m:
            m["_file"] = os.path.basename(p)
            entries.append(m)
    return entries


def is_public(m):
    return m.get("visibility", "") in PUBLIC_VIS and bool(m.get("live_url", "").strip())


def public_record(m):
    rec = {k: m.get(k, "") for k in PUBLIC_FIELDS}
    if m.get("repo_public"):
        rec["repo_url"] = m.get("repo_url", "")
    return rec


def write(path, content):
    with open(os.path.join(ROOT, path), "w", encoding="utf-8") as f:
        f.write(content)


def main():
    today = datetime.date.today().isoformat()
    entries = load_registry()
    shown = [m for m in entries if is_public(m)]
    omitted = [m for m in entries if not is_public(m)]

    # projects.json (public-safe fields only)
    write("projects.json", json.dumps([public_record(m) for m in shown], indent=2) + "\n")

    gen = "<!-- GENERATED by scripts/catalog_sync.py from registry/*.md — do not hand-edit. -->\n"

    # README.md
    r = [gen, "# EMN_labOS\n",
         "Personal umbrella OS for Malick Ndiaye's projects. The catalog below is generated "
         "from `registry/` and lists only projects that are public **and** live.\n",
         f"_Last generated: {today}_\n", "## Projects\n"]
    if shown:
        r.append("| Project | Summary | Stack | Live |")
        r.append("|---|---|---|---|")
        for m in shown:
            r.append(f"| {m['name']} | {m.get('summary','')} | {', '.join(m['stack'])} | [{m['live_url']}]({m['live_url']}) |")
    else:
        r.append("_No live public projects yet._")
    write("README.md", "\n".join(r) + "\n")

    # STATUS.md
    s = [gen, "# Status\n", f"_Last generated: {today}_\n",
         "| Project | Bucket | Status | Live |", "|---|---|---|---|"]
    for m in shown:
        s.append(f"| {m['name']} | {m['bucket']} | {m['status']} | [{m['live_url']}]({m['live_url']}) |")
    if not shown:
        s.append("| _none_ | | | |")
    write("STATUS.md", "\n".join(s) + "\n")

    # ROADMAP.md
    rm = [gen, "# Roadmap\n", f"_Last generated: {today}_\n",
          "Public projects grouped by status. Unlaunched/private projects are omitted by design.\n"]
    by_status = {}
    for m in shown:
        by_status.setdefault(m["status"], []).append(m["name"])
    if by_status:
        for st in sorted(by_status):
            rm.append(f"## {st}")
            for n in by_status[st]:
                rm.append(f"- {n}")
            rm.append("")
    else:
        rm.append("_No live public projects yet._")
    write("ROADMAP.md", "\n".join(rm) + "\n")

    # RELEASE-NOTES.md
    rn = [gen, "# Release notes\n", f"_Last generated: {today}_\n"]
    if shown:
        for m in shown:
            rn.append(f"- **{m['name']}** — live at [{m['live_url']}]({m['live_url']}).")
    else:
        rn.append("_No public releases yet._")
    write("RELEASE-NOTES.md", "\n".join(rn) + "\n")

    # docs/index.html (standalone, portfolio-reusable)
    cards = "\n".join(
        f'    <article class="card"><h2>{m["name"]}</h2><p>{m.get("summary","")}</p>'
        f'<p class="stack">{", ".join(m["stack"])}</p>'
        f'<a href="{m["live_url"]}">{m["live_url"]}</a></article>'
        for m in shown
    ) or '    <p>No live public projects yet.</p>'
    html = f"""<!doctype html>
<!-- GENERATED by scripts/catalog_sync.py — do not hand-edit. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EMN_labOS — Projects</title>
<style>
 body{{font-family:system-ui,sans-serif;max-width:880px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}}
 h1{{margin-bottom:.25rem}} .meta{{color:#666;font-size:.9rem}}
 .grid{{display:grid;gap:1rem;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));margin-top:1.5rem}}
 .card{{border:1px solid #e3e3e3;border-radius:12px;padding:1rem}}
 .card h2{{margin:.2rem 0;font-size:1.1rem}} .stack{{color:#666;font-size:.85rem}}
 .card a{{word-break:break-all}}
</style></head><body>
 <h1>EMN_labOS</h1>
 <p class="meta">Generated {today} — live public projects only.</p>
 <div class="grid">
{cards}
 </div>
</body></html>
"""
    write(os.path.join("docs", "index.html"), html)

    # summary
    print(f"catalog_sync: {len(shown)} shown, {len(omitted)} omitted.")
    for m in shown:
        print(f"  SHOWN   {m['name']} -> {m['live_url']}")
    for m in omitted:
        why = []
        if m.get("visibility", "") not in PUBLIC_VIS:
            why.append(f"visibility={m.get('visibility','') or 'unset'}")
        if not m.get("live_url", "").strip():
            why.append("no live_url")
        print(f"  OMITTED {m.get('name','?')} ({m.get('_file')}) — {', '.join(why)}")


if __name__ == "__main__":
    main()
