#!/usr/bin/env python3
"""
gen_manifest — emit manifest.sh (a sourceable clone list) from registry/*.md.

Source of truth: scripts/lib/registry.py (shared loader/validator).

POLICY (reconciled 2026-08 — code, docs, and reality now agree): the tracked, PUBLIC
manifest.sh lists clone lines ONLY for entries with `repo_public: true`. Private and
client repo URLs go in the gitignored `manifest.local.sh`, which bootstrap.sh also
sources. gen_manifest maintains manifest.local.sh on this machine as a convenience
(it is never committed — enforced by .gitignore).
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "lib"))
import registry as R  # noqa: E402


def main():
    entries, load_errors = R.load()
    errors = load_errors + R.validate(entries)
    if errors:
        print("gen_manifest: REGISTRY INVALID — refusing to generate:", file=sys.stderr)
        for e in errors:
            print(f"  ✗ {e}", file=sys.stderr)
        sys.exit(2)

    pub_rows, loc_rows, skipped = [], [], []
    for m in entries:
        url = (m.get("repo_url") or "").strip()
        bucket_dir = R.BUCKET_DIR.get(m.get("bucket", ""), "")
        if not url or not bucket_dir:
            skipped.append((m.get("slug", m.get("name", "?")),
                            "no repo_url" if not url else f"bad bucket '{m.get('bucket','')}'"))
            continue
        if not url.endswith(".git"):
            url += ".git"
        slug = m.get("slug") or m.get("name") or os.path.splitext(m["_file"])[0]
        row = f'clone_repo "{url}" "{bucket_dir}" "{slug}"'
        (pub_rows if m.get("repo_public") else loc_rows).append(row)

    pub = [
        "# GENERATED by scripts/gen_manifest.py from registry/*.md — do not hand-edit.",
        "# Sourced by scripts/bootstrap.sh. Signature: clone_repo <url> <bucket-dir> <slug>",
        "# PUBLIC manifest: repo_public entries only. Private/client clone lines live in the",
        "# gitignored manifest.local.sh (also maintained by this script, never committed).",
        "",
    ] + pub_rows
    with open(os.path.join(R.ROOT, "manifest.sh"), "w", encoding="utf-8") as f:
        f.write("\n".join(pub) + "\n")

    loc = [
        "# GENERATED by scripts/gen_manifest.py — GITIGNORED, machine-local. Never commit.",
        "# Private/client repo clone lines (kept out of the public manifest by policy).",
        "",
    ] + loc_rows
    with open(os.path.join(R.ROOT, "manifest.local.sh"), "w", encoding="utf-8") as f:
        f.write("\n".join(loc) + "\n")

    print(f"gen_manifest: {len(pub_rows)} public row(s) -> manifest.sh, "
          f"{len(loc_rows)} private row(s) -> manifest.local.sh")
    for slug, why in skipped:
        print(f"  SKIPPED {slug} — {why}")


if __name__ == "__main__":
    main()
