#!/usr/bin/env python3
"""
gen_roster — emit claude-output-docs/roster.md from .claude/agents/ + .claude/skills/.

The roster used to be produced by a step inside /labos-maintenance, which cut descriptions at a
fixed width (mid-word) and could drift from disk with nothing to catch it. It is now a generated
artifact with a `--check` gate, like the catalog.

Properties:
- Agents inherit the session's model. A file that pins a specific model is an ERROR: the roster
  would then imply an agent is limited to it. `model: inherit` or no model line at all is fine.
- Skills: name from the folder. A skill carrying `disable-model-invocation: true` is a command
  (side-effecting); one without it is reference (preloadable) — that flag is the real distinction,
  not prose.
- Descriptions are cut at a sentence boundary, never mid-word.
- `--check`: render in memory, diff against the file, exit 1 on drift, write nothing.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join("claude-output-docs", "roster.md")
GEN = "<!-- GENERATED by scripts/gen_roster.py from .claude/agents + .claude/skills — do not hand-edit. -->"
# Hand-maintained: retirements are history, not derivable from what is on disk.
RETIRED = ("Retired in the 2026-08 rebuild: `project-manager` (dead Telegram integration), "
           "`backend-eng` / `frontend-eng` (content → `templates/doc-kit/`), `qa` (superseded by "
           "`reviewer`).")
MAX_LEN = 150


def frontmatter(path):
    """Flat-scalar frontmatter of a markdown file, as {key: value}."""
    text = open(path, encoding="utf-8-sig").read()
    if not text.startswith("---"):
        return {}
    block = text.split("---", 2)[1]
    meta = {}
    for line in block.strip().splitlines():
        if ":" not in line or line.strip().startswith("#"):
            continue
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip().strip('"').strip("'")
    return meta


def summarise(desc):
    """First sentence, trimmed to MAX_LEN at a word boundary — never mid-word."""
    d = " ".join(desc.split())
    m = re.match(r"^(.*?[.!?])(\s|$)", d)
    if m and len(m.group(1)) >= 40:
        d = m.group(1)
    if len(d) > MAX_LEN:
        d = d[:MAX_LEN].rsplit(" ", 1)[0].rstrip(",;:—-") + "…"
    return d.replace("|", "\\|")


def render():
    agents, skills, errors = [], [], []
    for p in sorted(glob.glob(os.path.join(ROOT, ".claude", "agents", "*.md"))):
        meta = frontmatter(p)
        name = os.path.splitext(os.path.basename(p))[0]
        model = meta.get("model", "inherit").strip()
        if model != "inherit":
            errors.append(f"{os.path.relpath(p, ROOT)}: pins 'model: {model}' — agents inherit the "
                          f"session's model; use 'model: inherit' or drop the line")
        agents.append((name, summarise(meta.get("description", ""))))
    for d in sorted(glob.glob(os.path.join(ROOT, ".claude", "skills", "*"))):
        sk = os.path.join(d, "SKILL.md")
        if not os.path.isfile(sk):
            continue
        meta = frontmatter(sk)
        name = meta.get("name") or os.path.basename(d)
        kind = ("command (side-effecting)" if str(meta.get("disable-model-invocation", "")).lower() == "true"
                else "reference (preloadable)")
        skills.append((name, kind, summarise(meta.get("description", ""))))

    out = [GEN, "# labOS agent & skill roster", "",
           "Generated from `.claude/agents/*.md` and `.claude/skills/*/SKILL.md`. Every agent runs on",
           "the session's model — none is limited to a particular one.", "",
           f"## Agents ({len(agents)})", "", "| Agent | Role |", "|---|---|"]
    out += [f"| `{n}` | {d} |" for n, d in agents]
    out += ["", f"## Skills ({len(skills)})", "", "| Skill | Kind | Purpose |", "|---|---|---|"]
    out += [f"| `/{n}` | {k} | {d} |" for n, k, d in skills]
    out += ["", RETIRED]
    return "\n".join(out) + "\n", errors


def main():
    content, errors = render()
    if errors:
        print("gen_roster: INVALID agent/skill metadata — refusing to generate:", file=sys.stderr)
        for e in errors:
            print(f"  ✗ {e}", file=sys.stderr)
        sys.exit(2)
    full = os.path.join(ROOT, OUT)
    current = open(full, encoding="utf-8").read() if os.path.isfile(full) else None
    if "--check" in sys.argv:
        if current != content:
            print(f"gen_roster --check: DRIFT in {OUT}", file=sys.stderr)
            print("Fix: python3 scripts/gen_roster.py, then commit the result.", file=sys.stderr)
            sys.exit(1)
        print(f"gen_roster --check: clean ({OUT} matches .claude/).")
        return
    if current == content:
        print(f"gen_roster: {OUT} already current.")
        return
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"gen_roster: wrote {OUT}.")


if __name__ == "__main__":
    main()
