#!/usr/bin/env python3
"""
gen_manifest — emit manifest.sh (a sourceable clone list) from registry/*.md.

Source of truth: registry frontmatter (repo_url + bucket). Reuses catalog_sync's parser.
Filter: every registry entry that has a non-empty repo_url, regardless of visibility/live_url
(different from catalog_sync.py, which is default-deny on visibility+live_url for PUBLIC surfaces).

The private freelance entry has no repo_url in the registry by design, so it is excluded here;
it lives in the gitignored manifest.local.sh instead. Stdlib only.
"""
import os
from catalog_sync import load_registry, ROOT  # reuse the existing frontmatter parser

BUCKET_DIR = {"personal": "personal-projects", "freelance": "freelance-projects", "poc": "pocs"}


def main():
    rows = []
    for m in load_registry():
        url = (m.get("repo_url") or "").strip()
        bucket = BUCKET_DIR.get(m.get("bucket", ""), "")
        if not url or not bucket:
            continue
        if not url.endswith(".git"):
            url += ".git"
        slug = m.get("slug") or m.get("name") or os.path.splitext(m["_file"])[0]
        rows.append((url, bucket, slug))

    lines = [
        "# GENERATED by scripts/gen_manifest.py from registry/*.md — do not hand-edit.",
        "# Sourced by scripts/bootstrap.sh. Signature: clone_repo <url> <bucket-dir> <slug>",
        "",
    ]
    lines += [f'clone_repo "{u}" "{b}" "{s}"' for u, b, s in rows]
    with open(os.path.join(ROOT, "manifest.sh"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"gen_manifest: wrote {len(rows)} repo(s) to manifest.sh")
    for u, b, s in rows:
        print(f"  {s:16} {b:18} {u}")


if __name__ == "__main__":
    main()
